env:
- DISPLAY=:99.0
before_script:
- sh -e /etc/init.d/xvfb start
- sh .travis/scripts/install_chrome.sh
- sh .travis/scripts/setup_busterjs.sh
script:
- npm test
after_script:
- cat coverage_reports/coverage.lcov | ./node_modules/coveralls/bin/coveralls.js
language: node_js
node_js:
- 0.8